<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Notrelix.Domain.Tests</RootNamespace>
    <DomainTestProjectDirectory>$(MSBuildProjectDirectory)</DomainTestProjectDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Notrelix.Domain\Notrelix.Domain.csproj" />
    <ProjectReference Include="..\Notrelix.Testing.Core\Notrelix.Testing.Core.csproj" />
    <ProjectReference Include="..\Notrelix.Testing.Domain\Notrelix.Testing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None
        Update="Snapshots\**\*.approved.txt"
        CopyToOutputDirectory="PreserveNewest"
        CopyToPublishDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute
        Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>DomainTestProjectDirectory</_Parameter1>
      <_Parameter2>$(DomainTestProjectDirectory)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
