version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly, day: monday, time: "02:00"}
    target-branch: main
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /frontend
    schedule: {interval: weekly, day: monday, time: "02:30"}
    target-branch: main
    versioning-strategy: increase-if-necessary
    groups:
      frontend-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: nuget
    directory: /backend
    schedule: {interval: weekly, day: monday, time: "03:00"}
    target-branch: main
    groups:
      backend-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /backend
    schedule: {interval: weekly, day: monday, time: "03:30"}
    target-branch: main
