namespace Notrelix.Architecture.Tests;

public class RlsArchitectureTests
{
    private static string GetSolutionRoot()
    {
        var current = AppContext.BaseDirectory;
        while (current != null && !File.Exists(Path.Combine(current, "backend.slnx")))
        {
            current = Path.GetDirectoryName(current);
        }

        if (current is null)
            throw new DirectoryNotFoundException("Could not find backend.slnx root.");

        return current;
    }

    private static string GetInfrastructureRlsPath()
    {
        return Path.Combine(GetSolutionRoot(), "src", "Notrelix.Infrastructure", "Data", "Rls");
    }

    [Fact]
    public void RlsProductionCode_ShouldNotMutateDbCommandText()
    {
        var rlsFiles = Directory.GetFiles(GetInfrastructureRlsPath(), "*.cs", SearchOption.AllDirectories);
        var violations = new List<string>();

        foreach (var file in rlsFiles)
        {
            var lines = File.ReadAllLines(file);
            for (var i = 0; i < lines.Length; i++)
            {
                var line = lines[i];
                if (line.Contains(".CommandText =", StringComparison.Ordinal)
                    || line.Contains("command.CommandText", StringComparison.Ordinal))
                {
                    violations.Add($"{Path.GetRelativePath(GetSolutionRoot(), file)}:{i + 1}: {line.Trim()}");
                }
            }
        }

        violations.Should().BeEmpty(
            "RLS session state must be applied with explicit transaction-local set_config SQL, not by rewriting EF DbCommand.CommandText.");
    }

    [Fact]
    public void RlsPolicyApplier_ShouldNotGenerateBlanketWorkspacePolicies()
    {
        var applierPath = Path.Combine(GetInfrastructureRlsPath(), "RlsPolicyApplier.cs");
        var applier = File.Exists(applierPath) ? File.ReadAllText(applierPath) : string.Empty;

        applier.Should().NotContain("information_schema.columns",
            "RLS policies must be explicit table-group scripts, not generated for every table with workspace_id.");
        applier.Should().NotContain("workspace_access",
            "the old blanket workspace_access policy name must not be generated by production code.");
    }

    [Fact]
    public void RlsSqlScripts_ShouldNotGrantAppRoleInternalTableReads()
    {
        var internalTables = new[]
        {
            "events.domain_event_logs",
            "messaging.outbox_messages",
            "messaging.processed_events",
            "messaging.outbox_delivery_attempts",
            "notifications.email_outbox",
            "notifications.email_delivery_attempts",
            "audit.audit_logs",
            "audit.security_events",
            "ops.job_locks"
        };

        var sql = string.Join(
            "\n",
            Directory.GetFiles(GetInfrastructureRlsPath(), "*.sql", SearchOption.AllDirectories)
                .OrderBy(x => x)
                .Select(File.ReadAllText));

        var normalized = Regex.Replace(sql, @"\s+", " ").ToLowerInvariant();
        var violations = internalTables
            .Where(table => normalized.Contains($"grant select on {table} to notrelix_app", StringComparison.Ordinal)
                || normalized.Contains($"grant select, insert, update, delete on {table} to notrelix_app", StringComparison.Ordinal)
                || normalized.Contains($"grant all on {table} to notrelix_app", StringComparison.Ordinal))
            .ToList();

        violations.Should().BeEmpty(
            "notrelix_app must not be granted direct reads of internal events, messaging, email, audit, or job-lock tables.");
    }
}
