namespace Notrelix.Domain.Governance.Permissions;

public enum PermissionAction
{
    CreateWorkspace,
    ViewWorkspace,
    ManageWorkspace,
    ArchiveWorkspace,
    RestoreWorkspace,
    ViewMembers,
    InviteMember,
    ChangeMemberRole,
    RemoveMember,
    ManageWorkspaceSettings,
    ManageSpaces,
    ManageTeams,
    DeleteWorkspace,
    ViewBoard,
    CreateBoard,
    ManageBoardPermission,
    CreateBoardView,
    UpdateBoardView,
    ShareBoardView,
    CreateField,
    UpdateField,
    DeleteField,
    CreateItem,
    UpdateItem,
    MoveItem,
    AssignItem,
    SharePage,
    ManageBoard,
    ViewPage,
    UpdatePage,
    DeletePage
}
