#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, re
from pathlib import Path
from delivery_model import ROOT, component, load_catalog, load_images

SERVICE=re.compile(r'^[a-zA-Z0-9][a-zA-Z0-9_.-]*$')

def q(value: str) -> str:
    return json.dumps(value)

def main() -> int:
    p=argparse.ArgumentParser()
    p.add_argument('--application-manifest', type=Path)
    p.add_argument('--release-manifest', type=Path)
    p.add_argument('--output', required=True, type=Path)
    args=p.parse_args()
    if bool(args.application_manifest)==bool(args.release_manifest):
        raise SystemExit('provide exactly one manifest source')
    entries=[]
    if args.application_manifest:
        catalog=load_catalog(ROOT)
        app=json.loads(args.application_manifest.read_text())
        for a in app.get('artifacts',[]):
            cfg=component(catalog,a['component_id']); c=cfg.get('container',{})
            entries.append({'service':c.get('compose_service',''),'image':a.get('image','')})
        for _, lock in sorted(load_images(ROOT).get('images',{}).items()):
            if lock.get('class')=='runtime':
                entries.append({'service':lock.get('compose_service',''),'image':lock.get('ref','')})
    else:
        data=json.loads(args.release_manifest.read_text())
        images=data.get('images', data.get('release_images',{}).get('images',[]))
        for item in images:
            entries.append({'service':item.get('compose_service',''),'image':item.get('ref','')})
    seen=set(); lines=['# GENERATED by scripts/ci/render-release-compose.py. Do not commit rendered output.','services:']
    for e in sorted(entries,key=lambda x:x['service']):
        svc,ref=e['service'],e['image']
        if not SERVICE.fullmatch(svc): raise SystemExit(f'invalid/missing compose service: {svc!r}')
        if svc in seen: raise SystemExit(f'duplicate compose service: {svc}')
        if '@sha256:' not in ref: raise SystemExit(f'mutable release image for {svc}: {ref}')
        seen.add(svc); lines += [f'  {svc}:',f'    image: {q(ref)}']
        # Application build definitions in the base file must never survive a release override.
        if svc not in {'postgres','redis','rabbitmq','nginx'}: lines.append('    build: null')
    args.output.parent.mkdir(parents=True,exist_ok=True); args.output.write_text('\n'.join(lines)+'\n')
    return 0
if __name__=='__main__': raise SystemExit(main())
