// Generated surface

export type ConsumerSurfaceRow = {
  context: string;
  capability: string;
  consumerFile: string;
  consumerSymbol: string;

  classification:
    | "CANONICAL_MOCKED"
    | "COMPATIBILITY_GAP_MOCKED"
    | "CONTRACT_BLOCKED_UI_DISABLED"
    | "NOT_REACHABLE";

  operationId?: keyof import("../../packages/foundation/contracts/src/generated/rest/schema").operations;
  gapId?: `CTR-GAP-${string}`;

  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  pathTemplate?: string;

  mutation: boolean;
  canonicalReadProbe?: string;

  mockOperationId?: string;
  requiredE2ECase?: string;
};

export const ENABLED_CONSUMERS: ConsumerSurfaceRow[] = [
  {
    context: "TODO",
    capability: "TODO",
    consumerSymbol: "TODO",
    consumerFile: "frontend/apps/web/src/composition/application-services.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "TODO",
    mutation: false,
  },
  {
    context: "Account",
    capability: "endpoints.auth.profile",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/account/src/core/api/account.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.auth.profile",
    mutation: false,
  },
  {
    context: "Account",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/account/src/core/api/account.service.ts",
    capability: "Identity.Profile.UpdateProfile",
    operationId: "Identity.Profile.UpdateProfile",
    mutation: true,
  },
  {
    context: "Account",
    capability: "endpoints.users.preferences",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/account/src/core/api/account.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-ACC-PREFERENCES",
    method: "GET",
    pathTemplate: "endpoints.users.preferences",
    mutation: false,
  },
  {
    context: "Account",
    capability: "endpoints.users.preferences",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/account/src/core/api/account.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-ACC-PREFERENCES",
    method: "PATCH",
    pathTemplate: "endpoints.users.preferences",
    mutation: true,
  },
  {
    context: "Account",
    capability: "endpoints.users.security",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/account/src/core/api/account.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-ACC-SECURITY",
    method: "GET",
    pathTemplate: "endpoints.users.security",
    mutation: false,
  },
  {
    context: "Identity",
    capability: "endpoints.auth.login",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/auth/src/core/api/auth.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.auth.login",
    mutation: true,
  },
  {
    context: "Identity",
    capability: "endpoints.auth.register",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/auth/src/core/api/auth.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.auth.register",
    mutation: true,
  },
  {
    context: "Identity",
    capability: "endpoints.auth.logout",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/auth/src/core/api/auth.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.auth.logout",
    mutation: true,
  },
  {
    context: "Identity",
    capability: "endpoints.auth.refresh",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/auth/src/core/api/auth.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.auth.refresh",
    mutation: true,
  },
  {
    context: "Identity",
    capability: "endpoints.auth.forgotPassword",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/auth/src/core/api/auth.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.auth.forgotPassword",
    mutation: true,
  },
  {
    context: "Identity",
    capability: "endpoints.auth.resetPassword",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/auth/src/core/api/auth.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.auth.resetPassword",
    mutation: true,
  },
  {
    context: "Collaboration",
    capability: "TODO",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/collaboration/src/core/api/comment.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "TODO",
    mutation: true,
  },
  {
    context: "Collaboration",
    capability: "endpoints.comments.delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/collaboration/src/core/api/comment.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.comments.delete",
    mutation: true,
  },
  {
    context: "Governance",
    capability: "endpoints.roles.list",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/governance/src/core/api/governance.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.roles.list",
    mutation: false,
  },
  {
    context: "Governance",
    capability: "endpoints.roles.create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/governance/src/core/api/governance.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.roles.create",
    mutation: true,
  },
  {
    context: "Governance",
    capability: "endpoints.roles.update",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/governance/src/core/api/governance.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PUT",
    pathTemplate: "endpoints.roles.update",
    mutation: true,
  },
  {
    context: "Governance",
    capability: "endpoints.roles.delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/governance/src/core/api/governance.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.roles.delete",
    mutation: true,
  },
  {
    context: "Governance",
    capability: "endpoints.auditLogs.list",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/governance/src/core/api/governance.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.auditLogs.list",
    mutation: false,
  },
  {
    context: "Integrations",
    capability: "endpoints.connections.disconnect",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/integrations/src/core/api/integrations.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.connections.disconnect",
    mutation: true,
  },
  {
    context: "Integrations",
    capability: "endpoints.webhooks.list",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/integrations/src/core/api/integrations.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.webhooks.list",
    mutation: false,
  },
  {
    context: "Integrations",
    capability: "endpoints.webhooks.create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/integrations/src/core/api/integrations.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.webhooks.create",
    mutation: true,
  },
  {
    context: "Integrations",
    capability: "endpoints.webhooks.delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/integrations/src/core/api/integrations.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.webhooks.delete",
    mutation: true,
  },
  {
    context: "Notifications",
    capability: "endpoints.notifications.list",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/notifications/src/core/api/notifications.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.notifications.list",
    mutation: false,
  },
  {
    context: "Notifications",
    capability: "endpoints.notifications.unreadCount",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/notifications/src/core/api/notifications.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.notifications.unreadCount",
    mutation: false,
  },
  {
    context: "Notifications",
    capability: "endpoints.notifications.read",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/notifications/src/core/api/notifications.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.notifications.read",
    mutation: true,
  },
  {
    context: "Notifications",
    capability: "endpoints.notifications.readAll",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/notifications/src/core/api/notifications.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.notifications.readAll",
    mutation: true,
  },
  {
    context: "Notifications",
    capability: "endpoints.notifications.archive",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/notifications/src/core/api/notifications.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.notifications.archive",
    mutation: true,
  },
  {
    context: "Notifications",
    capability: "TODO",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/notifications/src/core/api/notifications.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PATCH",
    pathTemplate: "TODO",
    mutation: true,
  },
  {
    context: "Workspace",
    capability: "endpoints.workspaces.acceptInvitation",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/invitations.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.workspaces.acceptInvitation",
    mutation: true,
  },
  {
    context: "Workspace",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/members.service.ts",
    capability: "Workspaces.Members.ListMembers",
    operationId: "Workspaces.Members.ListMembers",
    mutation: false,
  },
  {
    context: "Workspace",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/members.service.ts",
    capability: "Workspaces.Members.UpdateMemberRole",
    operationId: "Workspaces.Members.UpdateMemberRole",
    mutation: true,
  },
  {
    context: "Workspace",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/members.service.ts",
    capability: "Workspaces.Members.RemoveMember",
    operationId: "Workspaces.Members.RemoveMember",
    mutation: true,
  },
  {
    context: "Workspace",
    capability: "/workspaces/${workspaceId}/views",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/views.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-WS-VIEWS",
    method: "GET",
    pathTemplate: "/workspaces/${workspaceId}/views",
    mutation: false,
  },
  {
    context: "Workspace",
    capability: "/workspaces/${workspaceId}/views/${viewId}",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/views.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-WS-VIEWS",
    method: "DELETE",
    pathTemplate: "/workspaces/${workspaceId}/views/${viewId}",
    mutation: true,
  },
  {
    context: "Workspace",
    capability: "/workspaces/${workspaceId}/views/reorder",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/views.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-WS-VIEWS",
    method: "POST",
    pathTemplate: "/workspaces/${workspaceId}/views/reorder",
    mutation: true,
  },
  {
    context: "Workspace",
    capability: "endpoints.workspaces.list",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/workspace.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.workspaces.list",
    mutation: false,
  },
  {
    context: "Workspace",
    capability: "endpoints.workspaces.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/workspace.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.workspaces.detail",
    mutation: false,
  },
  {
    context: "Workspace",
    capability: "endpoints.workspaces.list",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/features/workspace/src/core/api/workspace.service.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.workspaces.list",
    mutation: true,
  },
  {
    context: "Documents",
    capability: "endpoints.blocks.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/block.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.blocks.detail",
    mutation: true,
  },
  {
    context: "Documents",
    capability: "endpoints.blocks.reorder",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/block.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.blocks.reorder",
    mutation: true,
  },
  {
    context: "Documents",
    capability: "endpoints.comments.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/comment.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.comments.detail",
    mutation: true,
  },
  {
    context: "Documents",
    capability: "endpoints.pages.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/page.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.pages.detail",
    mutation: false,
  },
  {
    context: "Documents",
    capability: "endpoints.pages.breadcrumb",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/page.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.pages.breadcrumb",
    mutation: false,
  },
  {
    context: "Documents",
    capability: "endpoints.pages.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/page.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PATCH",
    pathTemplate: "endpoints.pages.detail",
    mutation: true,
  },
  {
    context: "Documents",
    capability: "endpoints.pages.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/page.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.pages.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardViews.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/board.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PUT",
    pathTemplate: "endpoints.boardViews.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.checklists",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/checklist.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.boardItems.checklists",
    mutation: false,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.checklists",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/checklist.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardItems.checklists",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.checklists.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/checklist.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PATCH",
    pathTemplate: "endpoints.checklists.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.checklists.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/checklist.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.checklists.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.checklists.items",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/checklist.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.checklists.items",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.checklistItems.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/checklist.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PATCH",
    pathTemplate: "endpoints.checklistItems.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.checklistItems.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/checklist.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.checklistItems.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardFields.create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/field.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardFields.create",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardFields.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/field.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.boardFields.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardFields.reorder",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/field.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardFields.reorder",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardGroups.create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/group.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardGroups.create",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardGroups.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/group.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PATCH",
    pathTemplate: "endpoints.boardGroups.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardGroups.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/group.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.boardGroups.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardGroups.duplicate",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/group.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardGroups.duplicate",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardGroups.reorder",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/group.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardGroups.reorder",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.comments.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item-comments.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PATCH",
    pathTemplate: "endpoints.comments.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "GET",
    pathTemplate: "endpoints.boardItems.detail",
    mutation: false,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardItems.create",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PATCH",
    pathTemplate: "endpoints.boardItems.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.detail",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.boardItems.detail",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.archive",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardItems.archive",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.duplicate",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardItems.duplicate",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.move",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardItems.move",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.fieldValues",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/item.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "PATCH",
    pathTemplate: "endpoints.boardItems.fieldValues",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boards.label",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/label.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.boards.label",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.labels",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/label.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "POST",
    pathTemplate: "endpoints.boardItems.labels",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "endpoints.boardItems.label",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/label.api.ts",
    classification: "COMPATIBILITY_GAP_MOCKED",
    gapId: "CTR-GAP-TODO",
    method: "DELETE",
    pathTemplate: "endpoints.boardItems.label",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardViews.Get",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardViews.Get",
    method: "GET", // dummy
    pathTemplate: "/api/v1/",
    mutation: false,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardViews.Save",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardViews.Save",
    method: "PUT", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardFields.Create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardFields.Create",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardFields.Update",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardFields.Update",
    method: "PATCH", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardFields.Delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardFields.Delete",
    method: "DELETE", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardFields.Reorder",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardFields.Reorder",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Labels.List",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Labels.List",
    method: "GET", // dummy
    pathTemplate: "/api/v1/",
    mutation: false,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Labels.Create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Labels.Create",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Labels.Update",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Labels.Update",
    method: "PATCH", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Labels.Delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Labels.Delete",
    method: "DELETE", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardGroups.Create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardGroups.Create",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardGroups.Update",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardGroups.Update",
    method: "PATCH", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardGroups.Delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardGroups.Delete",
    method: "DELETE", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardGroups.Duplicate",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardGroups.Duplicate",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardGroups.Reorder",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardGroups.Reorder",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.List",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.List",
    method: "GET", // dummy
    pathTemplate: "/api/v1/",
    mutation: false,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.Create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.Create",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.Update",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.Update",
    method: "PATCH", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.Delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.Delete",
    method: "DELETE", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.Archive",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.Archive",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.Duplicate",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.Duplicate",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.Move",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.Move",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.UpdateFieldValue",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.UpdateFieldValue",
    method: "PATCH", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.AddLabel",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.AddLabel",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.BoardItems.RemoveLabel",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.BoardItems.RemoveLabel",
    method: "DELETE", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Checklists.List",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Checklists.List",
    method: "GET", // dummy
    pathTemplate: "/api/v1/",
    mutation: false,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Checklists.Create",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Checklists.Create",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Checklists.Update",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Checklists.Update",
    method: "PATCH", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Checklists.Delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Checklists.Delete",
    method: "DELETE", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Checklists.CreateItemByChecklist",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Checklists.CreateItemByChecklist",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Checklists.UpdateItem",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Checklists.UpdateItem",
    method: "PATCH", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "WorkManagement.Checklists.DeleteItem",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "WorkManagement.Checklists.DeleteItem",
    method: "DELETE", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "Collaboration.Comments.GetBoardItemComments",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "Collaboration.Comments.GetBoardItemComments",
    method: "GET", // dummy
    pathTemplate: "/api/v1/",
    mutation: false,
  },
  {
    context: "Work Management",
    capability: "Collaboration.Comments.CreateBoardItemComment",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "Collaboration.Comments.CreateBoardItemComment",
    method: "POST", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "Collaboration.Comments.Update",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "Collaboration.Comments.Update",
    method: "PATCH", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },
  {
    context: "Work Management",
    capability: "Collaboration.Comments.Delete",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/work-management/state/src/api/",
    classification: "CANONICAL_MOCKED",
    operationId: "Collaboration.Comments.Delete",
    method: "DELETE", // dummy
    pathTemplate: "/api/v1/",
    mutation: true,
  },

  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/block.api.ts",
    capability: "Documents.Blocks.ListPageBlocks",
    operationId: "Documents.Blocks.ListPageBlocks",
    mutation: false,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/block.api.ts",
    capability: "Documents.Blocks.CreateBlock",
    operationId: "Documents.Blocks.CreateBlock",
    mutation: true,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/block.api.ts",
    capability: "Documents.Blocks.UpdateBlock",
    operationId: "Documents.Blocks.UpdateBlock",
    mutation: true,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/block.api.ts",
    capability: "Documents.Blocks.DeleteBlock",
    operationId: "Documents.Blocks.DeleteBlock",
    mutation: true,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/block.api.ts",
    capability: "Documents.Blocks.ReorderBlocks",
    operationId: "Documents.Blocks.ReorderBlocks",
    mutation: true,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/block.api.ts",
    capability: "Documents.Blocks.BatchUpdateBlocks",
    operationId: "Documents.Blocks.BatchUpdateBlocks",
    mutation: true,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/comment.api.ts",
    capability: "Collaboration.Comments.GetPageComments",
    operationId: "Collaboration.Comments.GetPageComments",
    mutation: false,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/comment.api.ts",
    capability: "Collaboration.Comments.CreatePageComment",
    operationId: "Collaboration.Comments.CreatePageComment",
    mutation: true,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/comment.api.ts",
    capability: "Collaboration.Comments.Resolve",
    operationId: "Collaboration.Comments.Resolve",
    mutation: true,
  },
  {
    context: "Documents",
    classification: "CANONICAL_MOCKED",
    consumerSymbol: "TODO",
    consumerFile: "frontend/packages/product/docs/state/src/api/history.api.ts",
    capability: "Documents.Pages.GetPageHistory",
    operationId: "Documents.Pages.GetPageHistory",
    mutation: false,
  },
];
