// Legacy hooks directory index.
// All hooks have been physically split and nested under their subdomains.
// Re-exporting from target locations for backwards compatibility within the feature.

export * from "../boards/hooks/queries/use-full-board"
export * from "../boards/hooks/queries/use-workspace-boards"
export * from "../boards/hooks/queries/use-resolved-workspace-board"
export * from "../boards/hooks/state/use-board-view"
export * from "../boards/hooks/state/use-board-kanban"
export * from "../boards/hooks/state/use-board-table"
export * from "../boards/hooks/state/use-kanban-filters"
export * from "../boards/hooks/state/use-kanban-search"
export * from "../boards/hooks/state/use-kanban-columns"
export * from "../boards/hooks/state/use-table-filters"
export * from "../boards/hooks/state/use-table-search"
export * from "../boards/hooks/state/use-table-sort"
export * from "../boards/hooks/mutations/use-create-kanban-column"
export * from "../boards/hooks/mutations/use-update-kanban-column"
export * from "../boards/hooks/mutations/use-delete-kanban-column"
export * from "../boards/hooks/mutations/use-reorder-kanban-columns"

export * from "../items/hooks/queries/use-card"
export * from "../items/hooks/queries/use-card-detail"
export * from "../items/hooks/queries/use-card-activity"
export * from "../items/hooks/queries/use-card-files"
export * from "../items/hooks/queries/use-card-comments"
export * from "../items/hooks/mutations/use-create-card"
export * from "../items/hooks/mutations/use-create-card-update"
export * from "../items/hooks/mutations/use-update-card"
export * from "../items/hooks/mutations/use-update-card-update"
export * from "../items/hooks/mutations/use-delete-card"
export * from "../items/hooks/mutations/use-delete-card-update"
export * from "../items/hooks/mutations/use-move-card"
export * from "../items/hooks/mutations/use-duplicate-card"
export * from "../items/hooks/mutations/use-update-field-value"
export * from "../items/hooks/mutations/use-upload-card-file"
export * from "../items/hooks/state/use-selected-card-panel"

export * from "../fields/hooks/queries/use-board-columns"
export * from "../fields/hooks/mutations/use-create-column"
export * from "../fields/hooks/mutations/use-update-column"
export * from "../fields/hooks/mutations/use-delete-column"
export * from "../fields/hooks/state/use-column-resize"
export * from "../fields/hooks/state/use-column-visibility"
export * from "../fields/hooks/state/use-resize-column"

export * from "../groups/hooks/queries/use-board-groups"
export * from "../groups/hooks/mutations/use-create-group"
export * from "../groups/hooks/mutations/use-update-group"
export * from "../groups/hooks/mutations/use-delete-group"
export * from "../groups/hooks/mutations/use-duplicate-group"
export * from "../groups/hooks/mutations/use-move-row"

export * from "../checklists/hooks/use-card-checklists"
