export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    profile: "/auth/me",
  },
  users: {
    updateProfile: "/users/profile",
  },
  workspaces: {
    list: "/workspaces",
    detail: (workspaceId: string) => `/workspaces/${workspaceId}`,
    invitationByToken: (token: string) => `/workspaces/invitations/by-token/${token}`,
    acceptInvitation: (token: string) => `/workspaces/invitations/accept/${token}`,
    pendingInvitations: "/workspaces/invitations/pending",
  },
  pages: {
    list: (workspaceId: string) => `/workspaces/${workspaceId}/pages`,
    tree: (workspaceId: string) => `/workspaces/${workspaceId}/pages/tree`,
    detail: (pageId: string) => `/pages/${pageId}`,
    breadcrumb: (pageId: string) => `/pages/${pageId}/breadcrumb`,
    blocks: (pageId: string) => `/pages/${pageId}/blocks`,
    comments: (pageId: string) => `/pages/${pageId}/comments`,
    history: (pageId: string) => `/pages/${pageId}/history`,
    search: (workspaceId: string) => `/workspaces/${workspaceId}/pages/search`,
    move: (pageId: string) => `/pages/${pageId}/move`,
  },
  blocks: {
    detail: (blockId: string) => `/blocks/${blockId}`,
    reorder: "/blocks/reorder",
    batch: (pageId: string) => `/pages/${pageId}/blocks/batch`,
  },
  boards: {
    listByWorkspaceId: (workspaceId: string) => `/workspaces/${workspaceId}/boards`,
    detail: (boardId: string) => `/boards/${boardId}`,
    full: (boardId: string) => `/boards/${boardId}/full`,
    view: (boardId: string) => `/boards/${boardId}/view`,
    columns: (boardId: string) => `/boards/${boardId}/columns`,
    column: (boardId: string, columnId: string) => `/boards/${boardId}/columns/${columnId}`,
    reorderColumns: (boardId: string) => `/boards/${boardId}/columns/reorder`,
    labels: (boardId: string) => `/boards/${boardId}/labels`,
    label: (boardId: string, labelId: string) => `/boards/${boardId}/labels/${labelId}`,
  },
  lists: {
    byBoard: (boardId: string) => `/boards/${boardId}/lists`,
    detail: (listId: string) => `/lists/${listId}`,
    cards: (listId: string) => `/lists/${listId}/cards`,
    duplicate: (listId: string) => `/lists/${listId}/duplicate`,
    archive: (listId: string) => `/lists/${listId}/archive`,
    reorder: (boardId: string) => `/boards/${boardId}/lists/reorder`,
  },
  cards: {
    detail: (cardId: string) => `/cards/${cardId}`,
    move: (cardId: string) => `/cards/${cardId}/move`,
    duplicate: (cardId: string) => `/cards/${cardId}/duplicate`,
    archive: (cardId: string) => `/cards/${cardId}/archive`,
    fieldValues: (cardId: string) => `/cards/${cardId}/field-values`,
    comments: (cardId: string) => `/cards/${cardId}/comments`,
    attachments: (cardId: string) => `/cards/${cardId}/attachments`,
    activity: (cardId: string) => `/cards/${cardId}/activity`,
    checklists: (cardId: string) => `/cards/${cardId}/checklists`,
    labels: (cardId: string) => `/cards/${cardId}/labels`,
    label: (cardId: string, labelId: string) => `/cards/${cardId}/labels/${labelId}`,
  },
  checklists: {
    detail: (checklistId: string) => `/checklists/${checklistId}`,
    items: (checklistId: string) => `/checklists/${checklistId}/items`,
  },
  checklistItems: {
    detail: (itemId: string) => `/checklist-items/${itemId}`,
  },
  comments: {
    detail: (commentId: string) => `/comments/${commentId}`,
  },
  notifications: {
    list: "/notifications",
    read: (id: string) => `/notifications/${id}/read`,
    readAll: "/notifications/read-all",
  },
};
