<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Notrelix.Testing.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Notrelix.Domain\Notrelix.Domain.csproj" />
    <ProjectReference Include="..\Notrelix.Testing.Core\Notrelix.Testing.Core.csproj" />
  </ItemGroup>

</Project>
