<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Notrelix.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Notrelix.Domain.Tests" />
  </ItemGroup>

  <!-- NO PACKAGES - Domain layer must be PURE according to Clean Architecture rules -->

</Project>
