export const routes = {
  home: "/",
  contact: "/contact",
  auth: {
    signIn: "/sign-in",
    register: "/sign-up",
    forgotPassword: "/forgot-password",
    terms: "/terms",
    privacy: "/privacy",
  },
  dashboard: {
    root: "/home",
    search: "/dashboard/search",
    notifications: "/dashboard/notifications",
    calendar: "/dashboard/calendar",
    settings: "/dashboard/settings",
    trash: "/dashboard/trash",
  },
  account: {
    root: '/account',
    profile: '/account/profile',
    appearance: '/account/appearance',
    security: '/account/security',
    notifications: '/account/notifications',
  },
  workspace: {
    root: (workspaceId: string) => `/${workspaceId}`,
    view: (workspaceId: string, view: string) => `/${workspaceId}?view=${view}`,
    chat: (workspaceId: string) => `/${workspaceId}/chat`,
    panel: (workspaceId: string, panel: string) => `/${workspaceId}?panel=${panel}`,
    page: (workspaceId: string, pageId: string) => `/${workspaceId}/docs/${pageId}`,
    settings: (workspaceId: string) => `/${workspaceId}?panel=settings`,
    members: (workspaceId: string) => `/${workspaceId}?panel=members`,
    permissions: (workspaceId: string) => `/${workspaceId}?panel=permissions`,
    billing: (workspaceId: string) => `/${workspaceId}?panel=billing`,
    docs: (workspaceId: string) => `/${workspaceId}/docs`,
    docsPage: (workspaceId: string, pageId: string) => `/${workspaceId}/docs/${pageId}`,
    docsHistory: (workspaceId: string, pageId: string) => `/${workspaceId}/docs/${pageId}/history`,
    boards: (workspaceId: string) => `/${workspaceId}/boards`,
    board: (workspaceId: string, boardId: string) => `/${workspaceId}/boards/${boardId}`,
  },
} as const;
