schema_version = 5

[images.dotnet-sdk]
class = "build"
source = "mcr.microsoft.com/dotnet/sdk:9.0.317"
ref = "mcr.microsoft.com/dotnet/sdk:9.0.317@sha256:f190d2dd9eef2899c91ac323caa0bd2b39334a5400ba93013e5199da39dad940"
stateful = false

[images.dotnet-aspnet]
class = "build"
source = "mcr.microsoft.com/dotnet/aspnet:9.0.20-bookworm-slim"
ref = "mcr.microsoft.com/dotnet/aspnet:9.0.20-bookworm-slim@sha256:779b0b298964fe93e6c6388c8bb823393a7c301b79cd5b3d80632bc886b2ffd4"
stateful = false

[images.node-build]
class = "build"
source = "node:22-alpine"
ref = "node:22-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32"
stateful = false

[images.nginx-build]
class = "build"
source = "nginx:alpine"
ref = "nginx:alpine@sha256:db35bfc6b2951e7f8a72db5db120288c127ffaeeb4a6d4b95a26fead017d5913"
stateful = false

[images.postgres]
class = "runtime"
source = "postgres:16.15-bookworm"
ref = "postgres@sha256:bb3e1a57e5407e0a5280b4211980a5e537f4abd234a87014ac979849a78dd825"
compose_service = "postgres"
deploy_env_var = "NOTRELIX_POSTGRES_IMAGE"
stateful = true

[images.redis]
class = "runtime"
source = "redis:7-alpine"
ref = "redis@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf"
compose_service = "redis"
deploy_env_var = "NOTRELIX_REDIS_IMAGE"
stateful = true

[images.rabbitmq]
class = "runtime"
source = "rabbitmq:4.3-management"
ref = "rabbitmq@sha256:57bddb6fbc3498b5d8b5a14dc6f4506073ebcf94c66ba2a7678c335faa8dd631"
compose_service = "rabbitmq"
deploy_env_var = "NOTRELIX_RABBITMQ_IMAGE"
stateful = true

[images.nginx]
class = "runtime"
source = "nginx:1.29-alpine-slim"
ref = "nginx@sha256:c9366b8c560169b101ca0e5422ed063b20779e6454c2326b9c9704225c9b0c08"
compose_service = "nginx"
deploy_env_var = "NOTRELIX_NGINX_IMAGE"
stateful = false

[images.playwright-ci]
class = "tooling"
source = "mcr.microsoft.com/playwright:v1.61.1-jammy"
ref = "mcr.microsoft.com/playwright:v1.61.1-jammy@sha256:7b86926fff94374389e8e1f4fdc5c76d050d4a06a7886bb537bf412b20e2b71e"
stateful = false
