schema_version = 6

[images.dotnet-sdk]
class = "build"
source = "mcr.microsoft.com/dotnet/sdk:9.0.317"
ref = "mcr.microsoft.com/dotnet/sdk:9.0.317@sha256:f190d2dd9eef2899c91ac323caa0bd2b39334a5400ba93013e5199da39dad940"
stateful = false

[images.dotnet-aspnet]
class = "build"
source = "mcr.microsoft.com/dotnet/aspnet:9.0.19-bookworm-slim"
ref = "mcr.microsoft.com/dotnet/aspnet:9.0.19-bookworm-slim@sha256:b1201ee0ccf9a22c06844982296c1be40d5ff9c7685dc002729f204e63fb1730"
stateful = false

[images.node-build]
class = "build"
source = "node:22-alpine"
ref = "node:22-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32"
stateful = false

[images.nginx-build]
class = "build"
source = "nginx:alpine"
ref = "nginx:alpine@sha256:db35bfc6b2951e7f8a72db5db120288c127ffaeeb4a6d4b95a26fead017d5913"
stateful = false

[images.postgres]
class = "runtime"
source = "postgres:16-alpine"
ref = "postgres@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685"
compose_service = "postgres"
deploy_env_var = "NOTRELIX_POSTGRES_IMAGE"
stateful = true

[images.redis]
class = "runtime"
source = "redis:7-alpine"
ref = "redis@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf"
compose_service = "redis"
deploy_env_var = "NOTRELIX_REDIS_IMAGE"
stateful = true

[images.rabbitmq]
class = "runtime"
source = "rabbitmq:3.13.5-management-alpine"
ref = "rabbitmq@sha256:49128afc207f5fcd1fc4a1878eb377911fcac2c2e89114e451890359f973b0dd"
compose_service = "rabbitmq"
deploy_env_var = "NOTRELIX_RABBITMQ_IMAGE"
stateful = true

[images.nginx]
class = "runtime"
source = "nginx:1.28-alpine"
ref = "nginx@sha256:a8b39bd9cf0f83869a2162827a0caf6137ddf759d50a171451b335cecc87d236"
compose_service = "nginx"
deploy_env_var = "NOTRELIX_NGINX_IMAGE"
stateful = false

[images.playwright-ci]
class = "tooling"
source = "mcr.microsoft.com/playwright:v1.61.1-jammy"
ref = "mcr.microsoft.com/playwright:v1.61.1-jammy@sha256:7b86926fff94374389e8e1f4fdc5c76d050d4a06a7886bb537bf412b20e2b71e"
stateful = false
