// Query key factory — single source of truth for all TanStack Query keys.
// Import from here in both hooks and server prefetch functions.

export const queryKeys = {
  auth: {
    all: ["auth"] as const,
    profile: ["auth", "profile"] as const,
  },
  account: {
    all: ["account"] as const,
    profile: ["account", "profile"] as const,
    preferences: ["account", "preferences"] as const,
    security: ["account", "security"] as const,
  },
  workspace: {
    all: ["workspaces"] as const,
    detail: (workspaceId: string) => ["workspaces", "detail", workspaceId] as const,
    snapshot: (workspaceId: string) => ["workspaces", "snapshot", workspaceId] as const,
    members: (workspaceId: string) => ["workspaces", "members", workspaceId] as const,
    views: (workspaceId: string) => ["workspaces", "views", workspaceId] as const,
    activeView: (workspaceId: string, view: string) => ["workspaces", "views", workspaceId, "active", view] as const,
    invitations: (workspaceId: string) => ["workspaces", "invitations", workspaceId] as const,
    invitationByToken: (token: string) => ["workspaces", "invitations", "by-token", token] as const,
    pendingInvitations: ["workspaces", "invitations", "pending"] as const,
    activity: (workspaceId: string) => ["workspaces", "activity", workspaceId] as const,
  },
  // Alias workspaces to workspace to satisfy both naming conventions safely
  workspaces: {
    all: ["workspaces"] as const,
    detail: (workspaceId: string) => ["workspaces", "detail", workspaceId] as const,
    snapshot: (workspaceId: string) => ["workspaces", "snapshot", workspaceId] as const,
    members: (workspaceId: string) => ["workspaces", "members", workspaceId] as const,
    views: (workspaceId: string) => ["workspaces", "views", workspaceId] as const,
    activeView: (workspaceId: string, view: string) => ["workspaces", "views", workspaceId, "active", view] as const,
    invitations: (workspaceId: string) => ["workspaces", "invitations", workspaceId] as const,
    invitationByToken: (token: string) => ["workspaces", "invitations", "by-token", token] as const,
    pendingInvitations: ["workspaces", "invitations", "pending"] as const,
    activity: (workspaceId: string) => ["workspaces", "activity", workspaceId] as const,
  },
  workManagement: {
    all: ["boards"] as const,
    list: (workspaceId: string) => ["boards", "list", workspaceId] as const,
    workspaceList: (workspaceId: string) => ["boards", "workspace", workspaceId] as const,
    fullBoard: (boardId: string, workspaceId?: string) => ["boards", "full", workspaceId ?? "workspace", boardId] as const,
    view: (workspaceId: string, boardId: string) => ["boards", "view", workspaceId, boardId] as const,
    groups: (workspaceId: string, boardId: string) => ["boards", "groups", workspaceId, boardId] as const,
    columns: (workspaceId: string, boardId: string) => ["boards", "columns", workspaceId, boardId] as const,
    cardDetail: (cardId: string) => ["cards", "detail", cardId] as const,
    cardUpdates: (cardId: string) => ["cards", "updates", cardId] as const,
    cardFiles: (cardId: string) => ["cards", "files", cardId] as const,
    cardComments: (cardId: string) => ["cards", "comments", cardId] as const,
    cardActivity: (cardId: string) => ["cards", "activity", cardId] as const,
  },
  // Keep boards and cards at root for backwards compatibility with legacy hooks
  boards: {
    all: ["boards"] as const,
    list: (workspaceId: string) => ["boards", "list", workspaceId] as const,
    workspaceList: (workspaceId: string) => ["boards", "workspace", workspaceId] as const,
    fullBoard: (boardId: string, workspaceId?: string) => ["boards", "full", workspaceId ?? "workspace", boardId] as const,
    view: (workspaceId: string, boardId: string) => ["boards", "view", workspaceId, boardId] as const,
    groups: (workspaceId: string, boardId: string) => ["boards", "groups", workspaceId, boardId] as const,
    columns: (workspaceId: string, boardId: string) => ["boards", "columns", workspaceId, boardId] as const,
  },
  cards: {
    detail: (cardId: string) => ["cards", "detail", cardId] as const,
    updates: (cardId: string) => ["cards", "updates", cardId] as const,
    files: (cardId: string) => ["cards", "files", cardId] as const,
    comments: (cardId: string) => ["cards", "comments", cardId] as const,
    activity: (cardId: string) => ["cards", "activity", cardId] as const,
  },
  docs: {
    all: ["pages"] as const,
    tree: (workspaceId: string) => ["pages", "tree", workspaceId] as const,
    list: (workspaceId: string) => ["pages", "list", workspaceId] as const,
    detail: (pageId: string) => ["pages", "detail", pageId] as const,
    breadcrumb: (pageId: string) => ["pages", "breadcrumb", pageId] as const,
    blocks: (pageId: string) => ["pages", "blocks", pageId] as const,
    comments: (pageId: string) => ["pages", "comments", pageId] as const,
    history: (pageId: string) => ["pages", "history", pageId] as const,
    search: (workspaceId: string, query: string) =>
      ["pages", "search", workspaceId, query] as const,
    favorites: (workspaceId: string) => ["pages", "favorites", workspaceId] as const,
  },
  // Keep pages for compatibility
  pages: {
    all: ["pages"] as const,
    tree: (workspaceId: string) => ["pages", "tree", workspaceId] as const,
    list: (workspaceId: string) => ["pages", "list", workspaceId] as const,
    detail: (pageId: string) => ["pages", "detail", pageId] as const,
    breadcrumb: (pageId: string) => ["pages", "breadcrumb", pageId] as const,
    blocks: (pageId: string) => ["pages", "blocks", pageId] as const,
    comments: (pageId: string) => ["pages", "comments", pageId] as const,
    history: (pageId: string) => ["pages", "history", pageId] as const,
    search: (workspaceId: string, query: string) =>
      ["pages", "search", workspaceId, query] as const,
    favorites: (workspaceId: string) => ["pages", "favorites", workspaceId] as const,
  },
  collaboration: {
    comments: (resourceId: string) => ["collaboration", "comments", resourceId] as const,
    mentions: (workspaceId: string) => ["collaboration", "mentions", workspaceId] as const,
    reactions: (resourceId: string) => ["collaboration", "reactions", resourceId] as const,
    presence: (workspaceId: string) => ["collaboration", "presence", workspaceId] as const,
    attachments: (resourceId: string) => ["collaboration", "attachments", resourceId] as const,
  },
  notifications: {
    all: ["notifications"] as const,
    unreadCount: ["notifications", "unread-count"] as const,
    preferences: ["notifications", "preferences"] as const,
  },
  billing: {
    all: ["billing"] as const,
    subscription: (workspaceId: string) => ["billing", "subscription", workspaceId] as const,
    invoices: (workspaceId: string) => ["billing", "invoices", workspaceId] as const,
    entitlements: (workspaceId: string) => ["billing", "entitlements", workspaceId] as const,
    usage: (workspaceId: string) => ["billing", "usage", workspaceId] as const,
  },
  governance: {
    all: ["governance"] as const,
    roles: (workspaceId: string) => ["governance", "roles", workspaceId] as const,
    permissions: (workspaceId: string) => ["governance", "permissions", workspaceId] as const,
    auditLogs: (workspaceId: string) => ["governance", "audit-logs", workspaceId] as const,
  },
  automation: {
    all: ["automation"] as const,
    rules: (workspaceId: string) => ["automation", "rules", workspaceId] as const,
    runs: (ruleId: string) => ["automation", "runs", ruleId] as const,
  },
  integrations: {
    all: ["integrations"] as const,
    connections: (workspaceId: string) => ["integrations", "connections", workspaceId] as const,
    webhooks: (workspaceId: string) => ["integrations", "webhooks", workspaceId] as const,
  },
  search: {
    global: (workspaceId: string, query: string) => ["search", "global", workspaceId, query] as const,
    recent: ["search", "recent"] as const,
  },
  activity: {
    all: ["activity"] as const,
    workspace: (workspaceId: string) => ["activity", "workspace", workspaceId] as const,
  },
} as const
