namespace Notrelix.Domain.SharedKernel.Ordering;

/// <summary>
/// Immutable value object representing a fractional ordering key.
/// Keys are generated by <see cref="FractionalIndexGenerator"/> and compared
/// using ordinal (case-sensitive, lexicographic) ordering.
/// </summary>
public sealed class FractionalIndex : ValueObject, IComparable<FractionalIndex>
{
    public string Value { get; }

    private FractionalIndex()
    {
        Value = null!;
    }

    private FractionalIndex(string value)
    {
        Value = value;
    }

    /// <summary>
    /// Creates a <see cref="FractionalIndex"/> from an existing key string.
    /// The key must conform to the canonical fractional-indexing grammar.
    /// No trimming is performed — whitespace is rejected, not normalized.
    /// </summary>
    public static FractionalIndex Create(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
        FractionalIndexGenerator.ValidateKey(value);
        return new FractionalIndex(value);
    }

    /// <summary>
    /// Returns the canonical initial key "a0".
    /// </summary>
    public static FractionalIndex Initial() => Create("a0");

    public int CompareTo(FractionalIndex? other)
    {
        if (ReferenceEquals(this, other))
            return 0;

        if (other is null)
            return 1;

        return StringComparer.Ordinal.Compare(Value, other.Value);
    }

    protected override IEnumerable<object?> GetEqualityComponents()
    {
        yield return Value;
    }

    public override string ToString() => Value;
}
